<?php
/**
 * @file
 * Main hooks.
 */

// Objects.
define('UTAILLA_COLLECTION', 'ailla:collection_collection');
define('UTAILLA_ORG_COLLECTION', 'ailla:organization_collection');
define('UTAILLA_ORG_CMODEL', 'ailla:organizationCModel');
define('UTAILLA_RESOURCE_CMODEL', 'ailla:resourceCModel');
define('UTAILLA_CONTRIBUTOR_COLLECTION', 'ailla:contributor_collection');
define('UTAILLA_CONTRIBUTOR_CMODEL', 'ailla:contributorCModel');
// Migrations.
define('UTAILLA_USER_MIGRATION', 'UtaillaUser');
define('UTAILLA_CONTACT_MIGRATION', 'UtaillaContact');
define('UTAILLA_LIMIT_FOR_RESOURCE_IMPORT', 100);
// Relationships.
define('UTAILLA_USER_REL', 'hasAssociatedUser');
define('UTAILLA_CONTACT_REL', 'hasAssociatedContact');

/**
 * Implements hook_islandora_required_objects().
 */
function utailla_islandora_required_objects(IslandoraTuque $connection) {
  module_load_include('inc', 'utailla', 'includes/utilities');
  $module_path = drupal_get_path('module', 'utailla');

  // Language content model.
  $language_cmodel = $connection->repository->constructObject('ailla:languageCModel');
  $language_cmodel->owner = 'fedoraAdmin';
  $language_cmodel->label = 'Ailla Language Content Model';
  $language_cmodel->models = 'fedora-system:ContentModel-3.0';
  utailla_set_ds_composite($language_cmodel, 'language_composite_model.xml');

  // Language collection.
  $language_collection = $connection->repository->constructObject('ailla:language_collection');
  $language_collection->owner = 'fedoraAdmin';
  $language_collection->label = 'Language Collection';
  $language_collection->models = 'islandora:collectionCModel';
  $language_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  utailla_set_collection_policy($language_collection, 'language_collection_policy.xml');
  utailla_set_default_thumb($language_collection);

  // Country content model.
  $country_cmodel = $connection->repository->constructObject('ailla:countryCModel');
  $country_cmodel->owner = 'fedoraAdmin';
  $country_cmodel->label = 'Ailla Country Content Model';
  $country_cmodel->models = 'fedora-system:ContentModel-3.0';
  utailla_set_ds_composite($country_cmodel, 'country_composite_model.xml');

  // Country collection.
  $country_collection = $connection->repository->constructObject('ailla:country_collection');
  $country_collection->owner = 'fedoraAdmin';
  $country_collection->label = 'Country Collection';
  $country_collection->models = 'islandora:collectionCModel';
  $country_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  utailla_set_collection_policy($country_collection, 'country_collection_policy.xml');
  utailla_set_default_thumb($country_collection);

  // Collection collection.
  $collection_collection = $connection->repository->constructObject(UTAILLA_COLLECTION);
  $collection_collection->owner = 'fedoraAdmin';
  $collection_collection->label = 'Collections';
  $collection_collection->models = 'islandora:collectionCModel';
  $collection_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  utailla_set_collection_policy($collection_collection, 'collection_collection_policy.xml');

  // Organization collection.
  $org_collection = $connection->repository->constructObject(UTAILLA_ORG_COLLECTION);
  $org_collection->owner = 'fedoraAdmin';
  $org_collection->label = 'Organizations';
  $org_collection->models = 'islandora:collectionCModel';
  $org_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  utailla_set_default_thumb($org_collection);
  utailla_set_collection_policy($org_collection, 'organization_collection_policy.xml');

  // Organization content model.
  $org_cmodel = $connection->repository->constructObject(UTAILLA_ORG_CMODEL);
  $org_cmodel->owner = 'fedoraAdmin';
  $org_cmodel->label = 'Organization Content Model';
  $org_cmodel->models = 'fedora-system:ContentModel-3.0';
  utailla_set_ds_composite($org_cmodel, 'organization_composite_model.xml');

  // Resource content model.
  $resource_cmodel = $connection->repository->constructObject(UTAILLA_RESOURCE_CMODEL);
  $resource_cmodel->owner = 'fedoraAdmin';
  $resource_cmodel->label = 'Resource Content Model';
  $resource_cmodel->models = 'fedora-system:ContentModel-3.0';
  utailla_set_ds_composite($resource_cmodel, 'resource_composite_model.xml');

  // Contributor collection.
  $contributor_collection = $connection->repository->constructObject(UTAILLA_CONTRIBUTOR_COLLECTION);
  $contributor_collection->owner = 'fedoraAdmin';
  $contributor_collection->label = 'Contributors';
  $contributor_collection->models = 'islandora:collectionCModel';
  $contributor_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  utailla_set_default_thumb($contributor_collection);
  utailla_set_collection_policy($contributor_collection, 'contributor_collection_policy.xml');

  // Contributor content model.
  $contributor_cmodel = $connection->repository->constructObject(UTAILLA_CONTRIBUTOR_CMODEL);
  $contributor_cmodel->owner = 'fedoraAdmin';
  $contributor_cmodel->label = 'Contributor Content Model';
  $contributor_cmodel->models = 'fedora-system:ContentModel-3.0';
  utailla_set_ds_composite($contributor_cmodel, 'contributor_composite_model.xml');

  return array(
    'utailla' => array(
      'title' => t('AILLA'),
      'objects' => array(
        $language_cmodel,
        $language_collection,
        $country_cmodel,
        $country_collection,
        $org_collection,
        $org_cmodel,
        $contributor_collection,
        $contributor_cmodel,
        $collection_collection,
        $resource_cmodel,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function utailla_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'utailla');
  return array(
    'Country MADS form' => array(
      'form_file' => "$module_path/xml/country_mads_form.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function utailla_islandora_xml_form_builder_form_associations() {
  return array(
    'ailla_country_mads_form' => array(
      'content_model' => 'ailla:countryCModel',
      'form_name' => 'Country MADS form',
      'dsid' => 'MADS',
      'title_field' => array('authority', 'english_name'),
      'transform' => FALSE,
      'template' => FALSE,
    ),
  );
}
